version: "3.9"
    
services:
  db:
    image: mysql:5.7
    ports: 
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./data/seed:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      UPLOAD_LIMIT: 64M
    
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./web:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_SITEURL: http://projecttitle.test
      WORDPRESS_HOME: http://projecttitle.test
    networks:
      default:
        aliases:
          - projecttitle.test
volumes:
  db_data: {}
  wordpress_data: {}
