name: Production

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - name: Install dependencies
      run: |
        composer install -o
        npm install

    - name: Build
      run: composer install
    
    - name: Deploy to Live server
      uses: burnett01/rsync-deployments@5.2
      with:
        switches: -avzr --exclude="data" --exclude=".git" --exclude=".github"
        remote_path: ${{ secrets.DEV_TARGET_LIVE }}
        remote_host: ${{ secrets.DEV_HOST }}
        remote_port: ${{ secrets.DEV_PORT }}
        remote_user: ${{ secrets.DEV_USER }}
        remote_key: ${{ secrets.DEV_DEPLOY_KEY }}